### PR TITLE
Update Vagrantfile

### PR DESCRIPTION
**Pull request by maexware-stefan**
Performance improvement, especially on load or huge projects

### CODE REVIEW

**Comment by PirxDanford** [comment]
Hello @maexware-stefan,
thank you very much for the improvement suggestion.

It looks like your commit is incomplete as it is missing the corresponding config values from the vm config in ansible/vars/default.yaml - a.e. if you look at `"--memory", vm_config["memory"],` you will find the corresponding value in the default.yaml at
```
vagrant_local:
  vm:
    memory: '512'
```

For us to be able to directly merge your suggestion please also commit the default.yml with the missing configuration values like
```
vagrant_local:
  vm:
    memory: '512'
    natdnshostresolver1: 'on'
```

**Comment by PirxDanford** [comment]
Hello again @maexware-stefan
Did you have any time to look into this?

**Comment by maexware-stefan** [comment]
added default.yml with settings, sry for the delay

**Comment by PirxDanford** [comment]
Thank you very much for the improvements. They will be included in the next patch release.

**Pull request merged**
