### PR TITLE
fix download of elasticsearch from SNI secured server

### PR DESCRIPTION
**Pull request by keywan-ghadami-oxid**

### CODE REVIEW

**Comment by PirxDanford** [comment]
Hi, it is nearly good, but as pip is not installed by default and also requires the setuptools I suggest to put something like that at the top of the install task:
```
---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: ensure python-setuptools are up to date
  become: yes
  apt:
    name: python-setuptools
    state: latest

- name: install python-pip
  become: yes
  apt:
    name: python-pip
    state: latest
```

Thanks!

**Comment by Sieg** [comment]
Or even better - add pip install role.

**Comment by keywan-ghadami-oxid** [comment]
I just copied what we have used in a project to make it working, I will ask @SvenBrunk if he can improve it to your needs.
@PirxDanford are you sure that is not already included in this PR as I see a change that includes `pip`:
```
- name: ensure pip is up to date
  become: yes
  pip:
    name:
      - pip
    state: latest
  tags:
    - elasticsearch
    - python
```

**Comment by PirxDanford** [comment]
@keywan-ghadami-oxid The "ensure pip is up to date" task relies on pip already being installed, which is not the case in our default setup. But Anton is right, this should go to a different role. If @SvenBrunk has no time, then I will take care, but this might take a while.

**Comment by SvenBrunk** [comment]
I would not separate the python package manager from python. The official docs say you should use the standard library to install pip first:
`python -m ensurepip --default-pip`
after that, pip is able to update itself:
`python -m pip install --upgrade pip setuptools`

**Comment by PirxDanford** [comment]
Merged the PR and added my suggested change on top. Thanks for the PR @keywan-ghadami-oxid and thanks for the feedback @SvenBrunk

**Pull request merged**
